# Generated by Django 4.2 on 2026-04-21 07:48

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0003_reading_constraints'),
        ('books', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ReviewLike',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('reader', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='review_likes', to='profiles.readerprofile', verbose_name='Читатель')),
                ('review', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='likes', to='profiles.review', verbose_name='Отзыв')),
            ],
            options={
                'verbose_name': 'Лайк отзыва',
                'verbose_name_plural': 'Лайки отзывов',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='BookLike',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('book', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='likes', to='books.book', verbose_name='Книга')),
                ('reader', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='book_likes', to='profiles.readerprofile', verbose_name='Читатель')),
            ],
            options={
                'verbose_name': 'Лайк книги',
                'verbose_name_plural': 'Лайки книг',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='BookComment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('text', models.TextField(max_length=2000, verbose_name='Текст комментария')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата обновления')),
                ('book', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='books.book', verbose_name='Книга')),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='replies', to='books.bookcomment', verbose_name='Родительский комментарий')),
                ('reader', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='book_comments', to='profiles.readerprofile', verbose_name='Читатель')),
            ],
            options={
                'verbose_name': 'Комментарий к книге',
                'verbose_name_plural': 'Комментарии к книгам',
                'ordering': ['created_at'],
            },
        ),
        migrations.AddConstraint(
            model_name='reviewlike',
            constraint=models.UniqueConstraint(fields=('reader', 'review'), name='books_review_like_unique_reader_review'),
        ),
        migrations.AddConstraint(
            model_name='booklike',
            constraint=models.UniqueConstraint(fields=('reader', 'book'), name='books_book_like_unique_reader_book'),
        ),
        migrations.AddIndex(
            model_name='bookcomment',
            index=models.Index(fields=['book', 'created_at'], name='books_bookc_book_id_0f5641_idx'),
        ),
        migrations.AddIndex(
            model_name='bookcomment',
            index=models.Index(fields=['parent', 'created_at'], name='books_bookc_parent__04f642_idx'),
        ),
    ]
