# Generated by Django 4.2 on 2026-03-13 11:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth_', '0002_alter_user_options_user_is_author'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='email_confirmed',
            field=models.BooleanField(default=False, verbose_name='Подтвержденный email'),
        ),
        migrations.AddField(
            model_name='user',
            name='telegram_confirmed',
            field=models.BooleanField(default=False, verbose_name='Подтвержденный Telegram'),
        ),
    ]
