# Generated by Django 4.2 on 2026-03-28 17:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth_', '0006_qrauthrequest_qr_code_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='telegram_id',
            field=models.BigIntegerField(blank=True, help_text='Telegram user ID for QR login', null=True, unique=True, verbose_name='Telegram ID'),
        ),
    ]
