# Generated by Django 4.2 on 2026-03-28 19:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auth_', '0003_add_role_simple'),
        ('auth_', '0009_final_fix'),
    ]

    operations = [
    ]
