# Generated by Django 4.2 on 2026-04-03 00:21

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ReaderProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('avatar', models.ImageField(blank=True, null=True, upload_to='avatars/readers/', verbose_name='Аватар')),
                ('is_active', models.BooleanField(default=True, help_text='Может ли пользователь использовать профиль', verbose_name='Активен')),
                ('books_read', models.PositiveIntegerField(default=0, verbose_name='Прочитано книг')),
                ('reviews_written', models.PositiveIntegerField(default=0, verbose_name='Написано отзывов')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата обновления')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='reader_profile', to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
            ],
            options={
                'verbose_name': 'Профиль читателя',
                'verbose_name_plural': 'Профили читателей',
                'ordering': ['-books_read'],
            },
        ),
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('rating', models.PositiveSmallIntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)], verbose_name='Рейтинг')),
                ('text', models.TextField(max_length=2000, verbose_name='Текст отзыва')),
                ('is_verified_purchase', models.BooleanField(default=False, verbose_name='Проверенная покупка')),
                ('helpful_count', models.PositiveIntegerField(default=0, verbose_name='Полезных голосов')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата обновления')),
                ('reader', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='profiles.readerprofile', verbose_name='Читатель')),
            ],
            options={
                'verbose_name': 'Отзыв',
                'verbose_name_plural': 'Отзывы',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ReadingHistory',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('started_at', models.DateTimeField(auto_now_add=True, verbose_name='Начало чтения')),
                ('finished_at', models.DateTimeField(blank=True, null=True, verbose_name='Окончание чтения')),
                ('last_page_read', models.PositiveIntegerField(default=0, verbose_name='Последняя прочитанная страница')),
                ('progress_percentage', models.PositiveIntegerField(default=0, validators=[django.core.validators.MaxValueValidator(100)], verbose_name='Процент прогресса')),
                ('is_completed', models.BooleanField(default=False, verbose_name='Завершено')),
                ('reader', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reading_history', to='profiles.readerprofile', verbose_name='Читатель')),
            ],
            options={
                'verbose_name': 'История чтения',
                'verbose_name_plural': 'Истории чтения',
                'ordering': ['-started_at'],
            },
        ),
        migrations.CreateModel(
            name='Bookmark',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('page_number', models.PositiveIntegerField(verbose_name='Номер страницы')),
                ('note', models.TextField(blank=True, max_length=500, verbose_name='Заметка')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('reader', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bookmarks', to='profiles.readerprofile', verbose_name='Читатель')),
            ],
            options={
                'verbose_name': 'Закладка',
                'verbose_name_plural': 'Закладки',
            },
        ),
        migrations.CreateModel(
            name='AuthorProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bio', models.TextField(blank=True, help_text='Краткая информация об авторе', max_length=2000, verbose_name='Биография')),
                ('website', models.URLField(blank=True, verbose_name='Веб-сайт')),
                ('telegram', models.CharField(blank=True, max_length=100, verbose_name='Telegram')),
                ('vkontakte', models.URLField(blank=True, verbose_name='ВКонтакте')),
                ('is_approved', models.BooleanField(default=False, help_text='Статус подтвержден модератором', verbose_name='Подтверждён автором')),
                ('requested_at', models.DateTimeField(blank=True, null=True, verbose_name='Дата запроса на статус автора')),
                ('approved_at', models.DateTimeField(blank=True, null=True, verbose_name='Дата подтверждения')),
                ('total_views', models.PositiveIntegerField(default=0, verbose_name='Всего просмотров')),
                ('total_sales', models.PositiveIntegerField(default=0, verbose_name='Всего продаж')),
                ('total_donations', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Всего донатов')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата обновления')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='author_profile', to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
            ],
            options={
                'verbose_name': 'Профиль автора',
                'verbose_name_plural': 'Профили авторов',
                'ordering': ['-total_views'],
            },
        ),
    ]
