# Generated by Django 4.2 on 2026-04-12 07:33

from django.db import migrations, models
import django.db.models.deletion


def add_books_relations_if_missing(apps, schema_editor):
    connection = schema_editor.connection
    introspection = connection.introspection

    Bookmark = apps.get_model('profiles', 'Bookmark')
    ReaderProfile = apps.get_model('profiles', 'ReaderProfile')
    ReadingHistory = apps.get_model('profiles', 'ReadingHistory')
    Review = apps.get_model('profiles', 'Review')
    Book = apps.get_model('books', 'Book')
    Genre = apps.get_model('books', 'Genre')

    with connection.cursor() as cursor:
        existing_tables = set(introspection.table_names(cursor))

    def get_columns(table_name):
        with connection.cursor() as cursor:
            description = introspection.get_table_description(cursor, table_name)
        return {column.name for column in description}

    def add_fk_if_missing(model, field_name, related_model, related_name, verbose_name):
        columns = get_columns(model._meta.db_table)
        column_name = f'{field_name}_id'
        if column_name in columns:
            return

        field = models.ForeignKey(
            related_model,
            on_delete=django.db.models.deletion.CASCADE,
            related_name=related_name,
            verbose_name=verbose_name,
            null=True,
            blank=True,
        )
        field.set_attributes_from_name(field_name)
        field.model = model
        schema_editor.add_field(model, field)

    add_fk_if_missing(Bookmark, 'book', Book, 'bookmarks', 'Книга')
    add_fk_if_missing(ReadingHistory, 'book', Book, 'reading_history', 'Книга')
    add_fk_if_missing(Review, 'book', Book, 'reviews', 'Книга')

    m2m_field = models.ManyToManyField(
        Genre,
        blank=True,
        related_name='readers',
        verbose_name='Предпочитаемые жанры',
    )
    m2m_field.contribute_to_class(ReaderProfile, 'preferred_genres')
    through_table = m2m_field.remote_field.through._meta.db_table

    if through_table not in existing_tables:
        schema_editor.create_model(m2m_field.remote_field.through)


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0001_initial'),
        ('profiles', '0001_initial'),
    ]

    operations = [
        migrations.SeparateDatabaseAndState(
            database_operations=[
                migrations.RunPython(add_books_relations_if_missing, migrations.RunPython.noop),
            ],
            state_operations=[
                migrations.AddField(
                    model_name='bookmark',
                    name='book',
                    field=models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name='bookmarks',
                        to='books.book',
                        verbose_name='Книга',
                    ),
                ),
                migrations.AddField(
                    model_name='readerprofile',
                    name='preferred_genres',
                    field=models.ManyToManyField(
                        blank=True,
                        related_name='readers',
                        to='books.genre',
                        verbose_name='Предпочитаемые жанры',
                    ),
                ),
                migrations.AddField(
                    model_name='readinghistory',
                    name='book',
                    field=models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name='reading_history',
                        to='books.book',
                        verbose_name='Книга',
                    ),
                ),
                migrations.AddField(
                    model_name='review',
                    name='book',
                    field=models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name='reviews',
                        to='books.book',
                        verbose_name='Книга',
                    ),
                ),
            ],
        ),
    ]
