# Generated by Django 4.2 on 2026-04-17 08:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0002_bookmark_book_readerprofile_preferred_genres_and_more'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='bookmark',
            constraint=models.UniqueConstraint(
                fields=('reader', 'book', 'page_number'),
                name='profiles_bookmark_unique_reader_book_page',
            ),
        ),
        migrations.AddConstraint(
            model_name='readinghistory',
            constraint=models.UniqueConstraint(
                fields=('reader', 'book'),
                name='profiles_reading_history_unique_reader_book',
            ),
        ),
        migrations.AddConstraint(
            model_name='review',
            constraint=models.UniqueConstraint(
                fields=('reader', 'book'),
                name='profiles_review_unique_reader_book',
            ),
        ),
    ]
