# Generated by Django 4.2 on 2026-04-21 08:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0003_reading_constraints'),
    ]

    operations = [
        migrations.AddField(
            model_name='readinghistory',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Дата обновления'),
        ),
    ]
