# Generated by Django 4.2 on 2026-05-03 08:45

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0002_reviewlike_booklike_bookcomment_and_more'),
        ('profiles', '0004_readinghistory_updated_at'),
    ]

    operations = [
        migrations.CreateModel(
            name='RecentBookView',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('viewed_count', models.PositiveIntegerField(default=1, verbose_name='Viewed count')),
                ('last_viewed_at', models.DateTimeField(auto_now=True, verbose_name='Last viewed at')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='First viewed at')),
                ('book', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recent_views', to='books.book', verbose_name='Book')),
                ('reader', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recent_book_views', to='profiles.readerprofile', verbose_name='Reader')),
            ],
            options={
                'verbose_name': 'Recently viewed book',
                'verbose_name_plural': 'Recently viewed books',
                'ordering': ['-last_viewed_at'],
            },
        ),
        migrations.CreateModel(
            name='AuthorSubscription',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('notify_new_books', models.BooleanField(default=True, verbose_name='Notify about new books')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Subscribed at')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subscribers', to='profiles.authorprofile', verbose_name='Author')),
                ('reader', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='author_subscriptions', to='profiles.readerprofile', verbose_name='Reader')),
            ],
            options={
                'verbose_name': 'Author subscription',
                'verbose_name_plural': 'Author subscriptions',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='recentbookview',
            index=models.Index(fields=['reader', '-last_viewed_at'], name='profiles_re_reader__b5a9be_idx'),
        ),
        migrations.AddConstraint(
            model_name='recentbookview',
            constraint=models.UniqueConstraint(fields=('reader', 'book'), name='profiles_recent_book_view_unique_reader_book'),
        ),
        migrations.AddIndex(
            model_name='authorsubscription',
            index=models.Index(fields=['author', 'notify_new_books'], name='profiles_au_author__e3cac8_idx'),
        ),
        migrations.AddIndex(
            model_name='authorsubscription',
            index=models.Index(fields=['reader', '-created_at'], name='profiles_au_reader__19df63_idx'),
        ),
        migrations.AddConstraint(
            model_name='authorsubscription',
            constraint=models.UniqueConstraint(fields=('reader', 'author'), name='profiles_author_subscription_unique_reader_author'),
        ),
    ]
